//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlinecinema
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class onlinecinemaEntities : DbContext
    {
        public static onlinecinemaEntities _context;
        public onlinecinemaEntities()
            : base("name=onlinecinemaEntities")
        {
        }

        public static onlinecinemaEntities GetContext()
        {
            if (_context == null)
            {
                _context = new onlinecinemaEntities();
            }
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Director> Directors { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<User_role> User_role { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Us_movie> Us_movie { get; set; }
        public virtual DbSet<Movie> Movies { get; set; }
    }
}
