//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlinecinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Us_movie
    {
        public int id_us_movie { get; set; }
        public int us { get; set; }
        public int mv { get; set; }
    
        public virtual User User { get; set; }
        public virtual Movie Movie { get; set; }
    }
}
